/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar3d: typeof import('./src/components/bar-3d/bar-3d.vue')['default']
    BlockTitle: typeof import('./src/components/home/block-title.vue')['default']
    Ct1: typeof import('./src/components/ct/ct-1.vue')['default']
    Ct2: typeof import('./src/components/ct/ct-2.vue')['default']
    Ct3: typeof import('./src/components/ct/ct-3.vue')['default']
    Ct4: typeof import('./src/components/ct/ct4.vue')['default']
    Ct5: typeof import('./src/components/ct/ct5.vue')['default']
    Ct6: typeof import('./src/components/ct/ct6.vue')['default']
    Ct7: typeof import('./src/components/ct/ct7.vue')['default']
    Ct8: typeof import('./src/components/ct/ct8.vue')['default']
    CtBlock: typeof import('./src/components/ct/ct-block.vue')['default']
    DateTime: typeof import('./src/components/date-time/date-time.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Flopper: typeof import('./src/components/flopper/flopper.vue')['default']
    FlopperNum: typeof import('./src/components/flopper/flopper-num.vue')['default']
    GHeader: typeof import('./src/components/g-header/g-header.vue')['default']
    GMap: typeof import('./src/components/guozi/g-map.vue')['default']
    Guo1: typeof import('./src/components/guozi/guo1.vue')['default']
    Guo2: typeof import('./src/components/guozi/guo2.vue')['default']
    Guo3: typeof import('./src/components/guozi/guo3.vue')['default']
    Guo4: typeof import('./src/components/guozi/guo4.vue')['default']
    Guo5: typeof import('./src/components/guozi/guo5.vue')['default']
    Guo6: typeof import('./src/components/guozi/guo6.vue')['default']
    Home1: typeof import('./src/components/hengtai-home/home-1.vue')['default']
    Home2: typeof import('./src/components/hengtai-home/home-2.vue')['default']
    Home3: typeof import('./src/components/hengtai-home/home-3.vue')['default']
    Home4: typeof import('./src/components/hengtai-home/home-4.vue')['default']
    Home5: typeof import('./src/components/hengtai-home/home-5.vue')['default']
    Home6: typeof import('./src/components/hengtai-home/home-6.vue')['default']
    Home7: typeof import('./src/components/home/home7.vue')['default']
    Home8: typeof import('./src/components/home/home8.vue')['default']
    ItemScroll: typeof import('./src/components/item-scroll/item-scroll.vue')['default']
    Kanban1: typeof import('./src/components/tgf-kanban/kanban1.vue')['default']
    Kanban2: typeof import('./src/components/tgf-kanban/kanban2.vue')['default']
    Kanban3: typeof import('./src/components/tgf-kanban/kanban3.vue')['default']
    Kanban5: typeof import('./src/components/tgf-kanban/kanban5.vue')['default']
    Kanban6: typeof import('./src/components/tgf-kanban/kanban6.vue')['default']
    Kanban7: typeof import('./src/components/tgf-kanban/kanban7.vue')['default']
    Kanban8: typeof import('./src/components/tgf-kanban/kanban8.vue')['default']
    KanbanDialog: typeof import('./src/components/tgf-kanban/kanban-dialog.vue')['default']
    KanbanHeader: typeof import('./src/components/tgf-kanban/kanban-header.vue')['default']
    Map: typeof import('./src/components/map/map.vue')['default']
    News: typeof import('./src/components/hengtai-home/news.vue')['default']
    Pie3d: typeof import('./src/components/Pie-3d/Pie-3d.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TgfHeader: typeof import('./src/components/tgf-header/tgf-header.vue')['default']
    XHeader: typeof import('./src/components/x-header/x-header.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
