/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar3d: typeof import('./components/bar-3d/bar-3d.vue')['default']
    BlockTitle: typeof import('./components/home/block-title.vue')['default']
    DateTime: typeof import('./components/date-time/date-time.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Flopper: typeof import('./components/flopper/flopper.vue')['default']
    FlopperNum: typeof import('./components/flopper/flopper-num.vue')['default']
    Home1: typeof import('./components/hengtai-home/home-1.vue')['default']
    Home2: typeof import('./components/hengtai-home/home-2.vue')['default']
    Home3: typeof import('./components/hengtai-home/home-3.vue')['default']
    Home4: typeof import('./components/hengtai-home/home-4.vue')['default']
    Home5: typeof import('./components/hengtai-home/home-5.vue')['default']
    Home6: typeof import('./components/hengtai-home/home-6.vue')['default']
    Home7: typeof import('./components/home/home7.vue')['default']
    Home8: typeof import('./components/home/home8.vue')['default']
    ItemScroll: typeof import('./components/item-scroll/item-scroll.vue')['default']
    Jinjian1: typeof import('./components/jinjian/jinjian1.vue')['default']
    Jinjian2: typeof import('./components/jinjian/jinjian2.vue')['default']
    Jinjian3: typeof import('./components/jinjian/jinjian3.vue')['default']
    Jinjian4: typeof import('./components/jinjian/jinjian4.vue')['default']
    Jinjian5: typeof import('./components/jinjian/jinjian5.vue')['default']
    Jinjian6: typeof import('./components/jinjian/jinjian6.vue')['default']
    Jinjian7: typeof import('./components/jinjian/jinjian7.vue')['default']
    Jinjian8: typeof import('./components/jinjian/jinjian8.vue')['default']
    JinjianHeader: typeof import('./components/jinjian/jinjian-header.vue')['default']
    Kanban1: typeof import('./components/tgf-kanban/kanban1.vue')['default']
    Kanban2: typeof import('./components/tgf-kanban/kanban2.vue')['default']
    Kanban3: typeof import('./components/tgf-kanban/kanban3.vue')['default']
    Kanban5: typeof import('./components/tgf-kanban/kanban5.vue')['default']
    Kanban6: typeof import('./components/tgf-kanban/kanban6.vue')['default']
    Kanban7: typeof import('./components/tgf-kanban/kanban7.vue')['default']
    Kanban8: typeof import('./components/tgf-kanban/kanban8.vue')['default']
    KanbanDialog: typeof import('./components/tgf-kanban/kanban-dialog.vue')['default']
    KanbanHeader: typeof import('./components/tgf-kanban/kanban-header.vue')['default']
    News: typeof import('./components/hengtai-home/news.vue')['default']
    Pie3d: typeof import('./components/Pie-3d/Pie-3d.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TgfHeader: typeof import('./components/tgf-header/tgf-header.vue')['default']
    XHeader: typeof import('./components/x-header/x-header.vue')['default']
  }
}
